# Generated by Django 2.2 on 2022-01-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Price', models.CharField(blank=True, max_length=50, null=True)),
                ('B_Lot', models.CharField(blank=True, max_length=50, null=True)),
                ('S_Lot', models.CharField(blank=True, max_length=50, null=True)),
                ('T_Lot', models.CharField(blank=True, max_length=50, null=True)),
                ('B_Frq', models.CharField(blank=True, max_length=50, null=True)),
                ('S_Frq', models.CharField(blank=True, max_length=50, null=True)),
                ('T_Frq', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ApaAja',
        ),
    ]
